name: Restart Render Every Monday
on:
  schedule:
    - cron: '5 0 * * 1'  # Every Monday at 12:05 AM UTC
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl https://api.render.com/deploy/srv-d3vf6h8dl3ps73fon7bg?key=8e6SGVtejHc
